language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

install:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]]; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --dev

script:
  - mkdir -p build/logs
  - phpdbg -qrr vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - composer require php-coveralls/php-coveralls
  - travis_retry vendor/bin/php-coveralls -v
